### ISSUE TITLE
Issue with leaflet definitions

### ISSUE THREAD

**Issue by LukeDetwiler** [markwh/streamstats#1]
Hey Mark,

Thanks for all this awesome work. This is the leaflet issue we came across on 4/1/2016. Assuming all of the necessary packages are loaded and proper timeout is allotted for the following lines of code:

# Delineate a watershed
_ws1 <- delineateWatershed(ylocation = 42.414214, xlocation = -72.535233, crs = 4326, 
                          includeparameters = "true")_
# Plot the watershed
_leafletWatershed(ws1)_

yield an error for leafletWatershed():
_Error in as.character(tools:::httpdPort) : 
  cannot coerce type 'closure' to vector of type 'character'_

If it helps, the delineateWatershed() call yielded the following warning messages:
_Warning messages:
1: In rbind_all(x, .id) : Unequal factor levels: coercing to character
2: In rbind_all(x, .id) : Unequal factor levels: coercing to character
3: In rbind_all(x, .id) : Unequal factor levels: coercing to character
4: In rbind_all(x, .id) : Unequal factor levels: coercing to character_

**Comment by markwh** [comment]
@LukeDetwiler For the error, looks like you need to update RStudio. See https://github.com/rstudio/shinyapps/issues/144#issuecomment-96289962

The warnings are nothing to worry about, but I should prevent them from showing up.

**Comment by markwh** [comment]
OK, warnings now gone with 0.0.1.9002
